language: node_js

node_js: 14

dist: trusty

sudo: required

cache:
  npm: false
  directories:
    - node_modules

install:
  - npm ci

notifications:
  email: true

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script: ng test --run-in-band --ci --bail=1

after_success:
  - npm run codecov
